<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectEEUnionIndicator_drpdn</name>
   <tag></tag>
   <elementGuidId>30849dd0-48e1-4aa5-a3a6-f36550cd9d24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>eeUnionIndicator</value>
   </webElementProperties>
</WebElementEntity>
