<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectEEExceptionCode2_drpdn</name>
   <tag></tag>
   <elementGuidId>b9b52715-da7d-43e1-9ae9-b21b33d3b5be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name = 'eeExceptionCode2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@name = 'eeExceptionCode1' and (text() = '   
										00
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
24
30
99' or . = '   
										00
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
24
30
99')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>eeExceptionCode1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>30</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-custom</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   
										00
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
24
30
99</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OcAcPanelContent&quot;)/div[@id=&quot;personal-data-right&quot;]/div[@class=&quot;data-row required&quot;]/div[@class=&quot;data-field&quot;]/select[@class=&quot;select-custom&quot;]</value>
   </webElementProperties>
</WebElementEntity>
